spring.mail.username=${EMAIL_USER_TEST}
spring.mail.password=${EMAIL_APP_PASS_TEST}
spring.data.mongodb.uri=${MONGO_LOCAL_TEST}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID_TEST}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET_TEST}
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URL_TEST}
razorpay.key.id=${RAZORPAY_ID_TEST}
razorpay.key.secret=${RAZORPAY_SECRET_TEST}
api.external-service.url=${FRONTEND_URL_TEST}