spring.mail.username=${EMAIL_USER_PROD}
spring.mail.password=${EMAIL_APP_PASS_PROD}
spring.data.mongodb.uri=${MONGO_ATLAS_PROD}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID_PROD}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET_PROD}
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URL_PROD}
razorpay.key.id=${RAZORPAY_ID_PROD}
razorpay.key.secret=${RAZORPAY_SECRET_PROD}