spring.application.name=Ecommerce
spring.security.oauth2.client.registration.google.scope=profile,email
# --- Razorpay Configuration ---
server.forward-headers-strategy=framework
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.profiles.active=test